### ISSUE TITLE
When the user deletes some data and press tab it doesn't rollback to the selected value as it should when it loses focus

### ISSUE THREAD

**Issue by melenaos** [CodyHouse/cd-select-autocomplete-changelog#1]
Steps:

- Click on the select box and select 'Ron Weasly'
- Delete the last 3 letters
- Press Tab 

What it does:

It leaves the text to 'Ron Wea'

What I was expecting:

To restore the selection to 'Ron Weasly'

Note:

If you delete the 3 letters and instead of tab you click somewhere else the Select rollback to 'Ron Weasly' as it should.

**Comment by claudia-romano** [comment]
Hi there,
we have just pushed a new version of the component that fixes this bug. You can get the updated code here:
https://codyhouse.co/ds/components/app/select-autocomplete

Cheers!
