### ISSUE TITLE
Clicking on the select it doesn't always open the options

### ISSUE THREAD

**Issue by melenaos** [CodyHouse/cd-select-autocomplete-changelog#2]
Steps:
- click on selectbox and select 'Harry Potter'
- While the selectbox is still focused click again

What is does:
It doesn't open the options

What i was expecting:
To open the options

Notes:
It opens the options only when it's gettings the focus from unfocus state

**Comment by claudia-romano** [comment]
Hi there,
thanks for the heads-up. We have fixed this issue. you will need to update the Autocomplete component as well:
https://codyhouse.co/ds/components/app/autocomplete

Cheers!
