### ISSUE TITLE
Z-Index doesn't working correctly

### ISSUE THREAD

**Issue by melenaos** [CodyHouse/cd-select-autocomplete-changelog#3]
Steps:
- Add, in the same page, two autocomplete select, one under the other.
- Open the first select

What is does:
It hides the options under the second autocomplete select

Notes:
I have tested with one 'Autocomplete' and under it an 'Autocomplete select'.

**Comment by claudia-romano** [comment]
Hi there,
thanks for the heads up. This has been fixed now. You'll need to update the css code of the Autocomplete component:
https://codyhouse.co/ds/components/app/autocomplete

Cheers!
