### ISSUE TITLE
[Suggestion] Provide events for onSelectionChange

### ISSUE THREAD

**Issue by melenaos** [CodyHouse/cd-select-autocomplete-changelog#4]
It would be great if you could provide some events at `SelectAuto` and possibly for `Autocomplete`.

The events I am looking after are `onChange` for `Autocomplete` and `onSelectChange` for `SelectAuto`.

The `onChange` would trigger when the underlying `input` changes value and `onSelectChange` would trigger when the user makes a selection from the options or type an option correctly.

**Comment by claudia-romano** [comment]
Hi there,
for the Autocomplete, you can use the native `input` event of the `js-autocomplete__input` element to detect when the input value changes.

For the Select Autocomplete, you can use the `change` event of the `js-select-auto__select` element (hidden select element).

Cheers!

**Comment by melenaos** [comment]
Thanks!
