### ISSUE TITLE
Component doesn't work or take into account options outside the optgroup

### ISSUE THREAD

**Issue by pgroot91** [CodyHouse/cd-select-autocomplete-changelog#6]
Component doesn't take into account the options that are not grouped into a optgroup.

Example:
```
<select name="cars" id="cars">
  <option value="spyker">Spyker</option>
  <option value="donkervoort">Donkervoort</option>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select>
```

The component will render/print only the list items within the optgroup.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We have pushed an updated version of the component that fixes this issue. You can get the updated JS code here:
https://codyhouse.co/ds/components/app/select-autocomplete

Cheers!
