### ISSUE TITLE
How can I retrieve the value and not the text ?

### ISSUE THREAD

**Issue by elecoest** [CodyHouse/cd-select-autocomplete-changelog#8]
Hello,

In your example 

https://codyhouse.co/ds/components/app/select-autocomplete

how can I retrieve 3 and not Ginny Weasley  like a standard select ?

Thanks

**Comment by claudia-romano** [comment]
Hi there, 
the native <select> element is updated each time you select an option in the autocomplete list. So you can get the value of the <select> element.

**Comment by elecoest** [comment]
Hello Claudia,

You spoke about this element : 

`<input class="form-control js-autocomplete__input js-select-auto__input" type="text" name="autocomplete-input-id" id="autocomplete-input-id" placeholder="e.g., Weasley" autocomplete="off">`

The answer is no, the element autocomplete-input-id get the text and not the value

**Comment by claudia-romano** [comment]
Hi, sorry I wasn't clear. I meant the `<select class="js-select-auto__select">` element. So you could do something like:
```
var select = document.getElementsByClassName('js-select-auto__select'); // make sure you are selecting the right <select> element
var value = select[0].value; // 3
```

If the `<select>` is inside a form, its value will be passed on form submission.

**Comment by elecoest** [comment]
Many thanks. It's work !

I propose you to explain this in your documentation page.  

Best regards

**Comment by claudia-romano** [comment]
Absolutely! We'll make sure to update the Info page. Cheers!
